### ISSUE TITLE
[Improvement]: on MPP video components

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_docs#19]
### Improvement

The [MPP system control API](https://gitee.com/kendryte/k230_docs/blob/main/zh/01_software/board/mpp/K230_%E7%B3%BB%E7%BB%9F%E6%8E%A7%E5%88%B6_API%E5%8F%82%E8%80%83.md) document lists the following video components:

`图像：视频输入（Video Input，简称VI），视频编码（Video Encoder，简称VENC），图像旋转（由GSDMA完成，简称DMA），深度处理单元(Depth Process Unit, 简称DPU)，图像解码（Video Decoder，简称VDEC），视频输出（Video Output，简称VO），虚拟视频输入（Virtual Video Input，简称VVI），虚拟视频输出（Virtual Video Output，简称VVO）`

However, I can't find answers myself regarding the following questions from the document:

- Where can we find some explanation regarding each list video component?
- What are the differences between VI and VVI?
- What are the differences between VO and VVO?
- Which component abstracts the function of ISP hardware?
- Above components list doesn't include VICAP, is VICAP a video component?
- Can one source be bound to multiple targets? For example, can VI be bound to both DPU and VO at the same time?

Hope the documents can be revised to give high level overview of the video components..

**Comment by LearnigF** [comment]
- I think you can refer to the hardware manual to understand the hardware information for each video component  [datasheet](https://github.com/kendryte/k230_docs/blob/main/zh/00_hardware/K230_datasheet.md)
- VVI is virtual video input, and VVO virtual video output is used to verify the availability of the multimedia framework on qemu in the early stage. 
- VI belongs to VICAP, and in terms of hardware, you can understand it as the CSI part. It is VICAP rather than VI that participates in system binding.
- VICAP includes Video input 、 ISP 、DW 
- A source can be bound to multiple targets, but multiple sources cannot be bound to the same target.

**Comment by yf13** [comment]
thanks!
